#!/usr/bin/env groovy

pipeline {
    agent any
    environment {
        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
        AWS_DEFAULT_REGION = "us-east-1"
    }
    stages {
        stage("Create an EKS Cluster") {
            steps {
                script {
                    dir('eks-cluster') {
                        sh "terraform init"
                        sh "terraform apply --auto-approve"
                    }
                }
            }
        }
        stage("Create prometheus") {
            steps {
                script {
                    dir('deployment') {
                        sh "kubectl apply -f prometheus.yaml"
                    }
                }
            }
        }

        stage("Create grafana") {
            steps {
                script {
                    dir('deployment') {
                        sh "kubectl apply -f grafana.yaml"
                    }
                }
            }
        }

        stage("Deploy adoptafriend-app to EKS") {
            steps {
                script {
                    dir('deployment') {
                        sh "kubectl apply -f adopt-a-friend.yaml"
                    }
                }
            }
        }

    
    }
}
